tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "awscli"
brew "bat"
brew "elixir"
brew "fish"
brew "fisher"
brew "git"
brew "lsd"
brew "httpie"
brew "htop"
brew "mas"
brew "mitmproxy"
brew "nvm"
brew "rbenv"
brew "starship"
brew "yarn"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

cask "1password"
cask "insomnia"
cask "1password-cli"
cask "android-platform-tools"
cask "android-studio"
cask "beekeeper-studio"
cask "docker"
# cask "fig" TODO: Evaluate if it's necessary
cask "figma"
cask "firefox"
cask "firefox-developer-edition"
cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"
cask "github"
cask "gitify"
cask "google-chrome"
cask "google-chrome-dev"
cask "handbrake"
cask "hyper"
cask "karabiner-elements"
cask "keycastr"
cask "homebrew/cask-drivers/logi-options-plus"
cask "mqtt-explorer"
cask "mqttx"
cask "obs"
cask "raycast"
cask "rectangle"
cask "safari-technology-preview"
cask "slack"
cask "stats"
cask "sourcetree"
cask "the-unarchiver"
cask "visual-studio-code"
cask "vlc"

mas "1Password for Safari", id: 1569813296
mas "Harvest", id: 506189836
mas "Hidden Bar", id: 1452453066
